
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t felix025/github-felix-next-js-app
    - run: echo "${{secrets.docker_token}}" | docker login -u ${{secrets.docker_name}} --password-stdin 
    - run: docker push felix025/github-felix-next-js-app:latest
