# name: Integration

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - name: "Installing Dependencies"
#       run: npm i

#     - name: "Build command"
#       run: npm run build

#   unit-tests:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - name: "Installing Dependencies"
#       run: npm i

#     - name: "Running test cases"
#       run: npm run test

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

#name indicates the use of this yml file as it is for integrating feature to the main branch hence integration
name: Integration

# on indicates the operation
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

#it lists all jobs to be performed it can single aur many.
jobs:
  #assigned building job ->run on machine? and versions of node to be supported .
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #all the steps github has to do when ask for build
    steps:
      #bydefault github is on main branch to make it make it move to current branch
      - uses: actions/checkout@v4
      #tells to use node.js specifically all the details mentioned in the strategy matrix which versions to be supported.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          #using npm to handle all packages.
          cache: "npm"
          #telling to install all the dependencies into the machine to run the code. which are invoking from package.json
      - name: "installing dependencies"
        run: npm ci
      - name: "build command"
        run: npm run build --if-present

  #.....
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    #all the steps github has to do when ask for build
    steps:
      #bydefault github is on main branch to make it make it move to current branch
      - uses: actions/checkout@v4
      #tells to use node.js specifically all the details mentioned in the strategy matrix which versions to be supported.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          #using npm to handle all packages.
          cache: "npm"
          #telling to install all the dependencies into the machine to run the code. which are invoking from package.json
      - name: "installing dependencies"
        run: npm ci
      - name: "Running test cases."

      - run: npm test
