# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Interation   // specify what this yml file is going to denote

on:         // on block siginfies on which event the jobs is going to trigger.....
  push:
    branches: [ "main" ] // whenever there is push or merge happening to main branch we still have to trigger those jobs  
  pull_request:
    branches: [ "main" ]      // The target branch is "main"

jobs:           // you can multiple jobs under this jobs
  build:          // you can name any name Like build 

    runs-on: ubuntu-latest  
     // specifying which particuale machine should GitHub used in their server
    // run-on property -> All jobs is not going to run on our local machine
    // All these jobs is going to run on GitHub Server

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]   // Run all these jobs on NodeJs 18,20 and 22
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:       // these are steps which github has to do to complete build is successfull (Any JOBS)
    // it tells github to checkout to current branch (features branch, By defauult it is on MAIN branch)
    - uses: actions/checkout@v4       // checkout to features branch
    // 
    - name: Use Node.js ${{ matrix.node-version }}      // optional
      uses: actions/setup-node@v4     // Setting up Node Environment before doing anything with project
      with:
        node-version: ${{ matrix.node-version }}   // Setting up with serveral node version i.e what strategy block means
        cache: 'npm'    // npm is easy way to handle all our packages
    - name: "Installing Dependencies"      // just for readability for other dev you can provide name for it 
      run: npm i           // this command install all dependencies (package.json)
    - run: npm run build

    // The FIRST JOB IS DONE (BUILD)     // JUST MAKE SURE YOUR INDENTATION IS PERFECT

  
  Unit testing:

    runs-on: ubuntu-latest      // we wanted to run on particular server

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Install Dependencies" 
    run: nmp i
    - name: "running test cases"
    run: npm run test        // Go to package.json which script we want to execute...

    
  



