#name of the file
name: Integration

on:
  push:
    branches: [ "main" ]
    #on the pull request as the target branch is main, it will trigger
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #these jobs are run on the github servers 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    #tells github to checkout to the current branch
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    #to setup the node enviornment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #to handle the pacages
        cache: 'npm'

        
    - name: "Installing Dependencies"
      run: npm i

    - name: "Build command"
      run: npm run build

  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Installing Dependencies"
      run: npm i

    - name: "Running test cases"
      run: npm run test